CREATE TABLE users (
   id INT GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(50),
   category VARCHAR(50),
   description VARCHAR(50),
   price FLOAT,
   url VARCHAR(100),
   lastUpdated DATE,
   pictureUrl VARCHAR(100)
);